name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      # Naya: IS_ANDROID_BUILD variable jodd diya hai
      - name: Next.js Build
        run: npm run build
        env:
          IS_ANDROID_BUILD: true

      - name: Ensure Out Directory
        run: |
          mkdir -p out
          touch out/index.html

      - name: Capacitor Sync
        run: |
          npx cap add android || true
          npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BaseKey-Debug-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
